import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_excel("CleanedData.xlsx")

print(data.head())
print("\n===== Dataset Information =====")
data.info()


cols=["Quantity","UnitPrice","ItemsInCart","TotalPrice"]

#basic statistics
print("\n===== BASIC STATISTICS =====\n")
print(data[cols].describe())
    

#Distribution Analysis
print("\n===== DISTRIBUTION ANALYSIS =====\n")
for i in cols:
    skw=data[i].skew()
    if -0.5<=skw<=0.5:
        print(f"{i} : Approximately Symmetric Distribution")
    elif skw>0.5:
        print(f"{i} : Positively Skewed Distribution")
    else:
        print(f"{i} : Negatively Skewed Distribution")


#outliers detection using IQR
print("\n===== OUTLIER DETECTION USING IQR =====\n")
for i in cols:
    Q1=data[i].quantile(0.25)
    Q3=data[i].quantile(0.75)
    IQR=Q3-Q1

    lower_bound=Q1-(1.5*IQR)
    upper_bound=Q3+(1.5*IQR)

    outliers=data[(data[i]<lower_bound)|(data[i]>upper_bound)]

    print(f"\nOutliers in {i}: {len(outliers)}")


#Correlation Values
print("\n=====Correlation Matrix=====")
print(data[cols].corr())

#Trends & FILTERING
print("\n=====Trends of the dataset after FILTERING (Removing Cancelled and Returned Order status):=====\n")

filter_Order=data[~((data["OrderStatus"]=="Cancelled") | (data["OrderStatus"]=="Returned"))]

pdt_quantity=filter_Order.groupby('Product')['Quantity'].sum().sort_values(ascending=False)
print(f"Trend of Product bought is :\n {pdt_quantity}\n")

pdt_revenue=filter_Order.groupby('Product')['TotalPrice'].sum().sort_values(ascending=False)
print(f"Revenue generated by each product is :\n {pdt_revenue}\n")

filter_order_coupon=filter_Order[~(filter_Order['CouponCode']=="NO COUPON")]

revenue_nocoupon=filter_order_coupon.groupby('Product')['TotalPrice'].sum().sort_values(ascending=False)
print(f"Revenue generated by the product excluding 'NO COUPON' orders :\n {revenue_nocoupon}\n")

paymt_method=filter_Order.groupby('Product')['PaymentMethod'].value_counts()
print(f"Trends of Payment method  :\n {paymt_method}\n")

print(f"Trends of Order Status :\n {data.groupby('Product')['OrderStatus'].value_counts()}\n")

print(f"Trends of Coupon Code  :\n {filter_Order.groupby('Product')['CouponCode'].value_counts()}\n")

print(f"Trends of Referral Sources :\n {filter_Order.groupby('Product')['ReferralSource'].value_counts()}\n")


#Key Insights 
print("\n=====KEY INSIGHTS FROM THE DATASET AFTER FILTERING=====\n")
print(f"Most Bought Product is :\n {pdt_quantity.head(1)}\n")
print(f"Maximum Revenue generated by the product is :\n {pdt_revenue.head(1)}\n")
print(f"Maximum Revenue generated by the product excluding 'NO COUPON' is :\n {revenue_nocoupon.head(1)}\n")
print(f"Most used Payment method is :\n {paymt_method.head(1)}\n")
print(f"Most Order Status is :\n {data['OrderStatus'].value_counts().head(1)}\n")
print(f"Most used Coupon Code is :\n {filter_Order['CouponCode'].value_counts().head(1)}\n")
print(f"Most used Referral Sources is :\n {filter_Order['ReferralSource'].value_counts().head(1)}\n")
monthly_sales = (
    data.groupby(data['Date'].dt.to_period('M'))['TotalPrice']
    .sum()
)
print("Monthly Sales Total Revenue Generated Trend")
print(monthly_sales)