import pandas as pd
import sqlite3

#excel file read
df=pd.read_csv("csv_cleaned_dataset.csv")

#database connection
conn=sqlite3.connect("Sales.db")

#create table into the database
df.to_sql("SalesData",conn,if_exists="replace", index=False)

#SQL QUERIES

query="SELECT * FROM SALESDATA LIMIT 5";
print(pd.read_sql(query,conn).to_string(index=False))


query = """
SELECT SUM(TotalPrice) AS Total_Revenue
FROM SalesData
WHERE OrderStatus NOT IN ('Cancelled', 'Returned')
"""
print("\nTotal Revenue from the data set")
print(pd.read_sql(query, conn).to_string(index=False))


query="""
SELECT Product,
       SUM(Quantity) AS Total_Quantity_Sold
FROM SalesData
WHERE OrderStatus NOT IN ('Cancelled', 'Returned')
GROUP BY Product
ORDER BY Total_Quantity_Sold DESC
"""
print("\nQuantity Sold by Product")
print(pd.read_sql(query, conn).to_string(index=False))


query = """
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM SalesData
WHERE OrderStatus NOT IN ('Cancelled', 'Returned')
GROUP BY Product
ORDER BY Revenue DESC
"""
print("\nRevenue Generated by each Product")
print(pd.read_sql(query, conn).to_string(index=False))


query = """
SELECT Product,
    AVG(TotalPrice) AS Average_Order_Value
FROM SalesData
WHERE OrderStatus NOT IN ('Cancelled', 'Returned')
GROUP BY Product
ORDER BY Average_Order_Value DESC
"""
print("\nAverage Order Value")
print(pd.read_sql(query, conn).to_string(index=False))


query = """
SELECT PaymentMethod,
       COUNT(*) AS Total_Orders
FROM SalesData
WHERE OrderStatus NOT IN ('Cancelled', 'Returned')
GROUP BY PaymentMethod
ORDER BY Total_Orders DESC
"""
print("\nOrders by Payment Method")
print(pd.read_sql(query, conn).to_string(index=False))


query = """
SELECT OrderStatus,
       COUNT(*) AS Order_Count
FROM SalesData
GROUP BY OrderStatus
ORDER BY Order_Count DESC
"""
print("\nOrder Status")
print(pd.read_sql(query, conn).to_string(index=False))

query = """
SELECT ReferralSource,
       COUNT(*) AS Orders
FROM SalesData
GROUP BY ReferralSource
ORDER BY Orders DESC
"""
print("\nOrders by Referral Source")
print(pd.read_sql(query, conn).to_string(index=False))

query = """
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM SalesData
WHERE OrderStatus='Delivered'
GROUP BY Product
ORDER BY Revenue DESC
"""
print("\nRevenue Generated by Delivered Products")
print(pd.read_sql(query, conn).to_string(index=False))

query = """
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM SalesData
WHERE OrderStatus = 'Cancelled'
GROUP BY Product
ORDER BY Revenue DESC
"""
print("\nRevenue Blocked due to Cancellations")
print(pd.read_sql(query, conn).to_string(index=False))

query = """
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM SalesData
WHERE OrderStatus='Returned'
GROUP BY Product
ORDER BY Revenue DESC
"""
print("\nRevenue Blocked due to Returned the products")
print(pd.read_sql(query, conn).to_string(index=False))


query = """
SELECT Product ,
       SUM(TotalPrice) as Revenue
FROM SalesData
WHERE (CouponCode !="NO COUPON") AND (OrderStatus NOT IN ('Cancelled', 'Returned'))
GROUP BY Product
ORDER BY Revenue DESC
"""
print("\nRevenue from Orders Using Coupons (Excluding NO COUPON)")
print(pd.read_sql(query, conn).to_string(index=False))


query = """
SELECT CustomerID,
       SUM(TotalPrice) AS Total_Spent
FROM SalesData
WHERE OrderStatus NOT IN ('Cancelled', 'Returned')
GROUP BY CustomerID
ORDER BY Total_Spent DESC
LIMIT 5
"""
print("\nTop 5 Customers")
print(pd.read_sql(query, conn).to_string(index=False))

query = """
SELECT PaymentMethod,
       SUM(TotalPrice) AS Revenue
FROM SalesData
WHERE OrderStatus NOT IN ('Cancelled', 'Returned')
GROUP BY PaymentMethod
ORDER BY Revenue DESC
"""
print("\nRevenue by Payment Method")
print(pd.read_sql(query, conn).to_string(index=False))

conn.close()